#!/usr/bin/env bash
# turns name to commit
# usage: name2commit "name"

echo "Looking for '$1'..."

#commit=$(git log origin/deprecated/android-3.4 --| grep -iB5 "$1" | grep "commit " | sed 's/commit\ //')

cd ../baffinlite

commit=$(git log | grep -iB5 "$1" | grep "commit " | sed 's/commit\ //')

echo "Found: $commit"

#git cherry-pick $commit

cd ../common

wget https://github.com/knuxdroid/android_kernel_samsung_baffinlite/commit/$commit.patch
git am $commit.patch
rm $commit.patch
