#!/usr/bin/env bash
# turns name to commit
# if multiple commits are found, returns the latest one
# usage: name2commit "name"

commit=$(git log origin/deprecated/android-3.4 -- | grep -iFB5 "$1" | grep "commit " | sed 's/commit\ //' | head -n1)

if [[ $commit ]]; then
	echo "$commit"
else
	exit 1
fi

git cherry-pick $commit
